### PR TITLE
make href relative in case of reverse proxy path prefix;

### PR DESCRIPTION
**Pull request by qrkourier**

### CODE REVIEW

**Comment by iphoting** [comment]
Would using the following line achieve the same effect?
```
<base href='.'>
```

Patch:
```
diff --git a/views/layout.haml b/views/layout.haml
index 0e74864..a4b7b02 100644
--- a/views/layout.haml
+++ b/views/layout.haml
@@ -1,6 +1,7 @@
 !!! 5
 %html
   %head
+    %base{ :href => '.' }
     %meta{ :name => 'viewport', :content => "width=device-width, initial-scale=1.0" }
     %link{ :rel => 'stylesheet', :href => '//netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css' }
     %link{ :res => 'stylesheet', :href => '//netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css' }
```

**Comment by qrkourier** [comment]
I determined that adding the %base header did not cause HREFs to inherit the relative path. To test this I reset my deployed branch to origin master HEAD and applied the prescribed patch. Now, instead of HREFs relative to the root of the requested path, all URLs are assuming the request path prefix is '/' as before the changes in my pull request.

**Comment by iphoting** [comment]
May I know which reverse proxy are you using? This request is quite strange.

**Comment by iphoting** [comment]
Please test with the `relative-href` branch. It works with my setup here.

**Comment by qrkourier** [comment]
I'm using Nginx as a reverse proxy. Nginx listens for requests on the same computer where pwqgen-web is running. Requests to the proxy for '/pwqgen' on the outside interface are fulfilled by the upstream (Sinatra) on 127.0.0.1:4567.

I checked out relative-href but the result was the same. The links in the HTML are not subordinate to '/pwqgen', but are top level.

This causes me to wonder whether I need to configure Nginx differently. It's possible that it is stripping that path prefix before the request reaches Sinatra.

**Comment by iphoting** [comment]
Consider this discussion here: <http://serverfault.com/questions/379675/nginx-reverse-proxy-url-rewrite>.
If you like, please post your Nginx `proxy_pass` config snippet here.

**Comment by qrkourier** [comment]
I am doing this:
```
location /pwqgen/ {
  proxy_pass http://localhost:4567/;
  proxy_set_header X-Forwarded-Host $host;
}
```
This strips the part of the URL matching location before sending the request to upstream. The proxy does not attempt to match patterns in the body of the response, only headers, so there is not an opportunity for the proxy to correct the HREFs generated by the app in the HTML document. It appears that the app is generating absolute HREFs, and I believe that if they were relative then the browser would infer the correct absolute HREF.

For example, the app generates this HTML currently, and so the URL is invalid when the proxy expects a path root of "http://foo.example.com/pwqgen":
```
        <a href='http://foo.example.com/'>pwqgen</a>
        <a href='http://foo.example.com/m'>/m</a>
        <a href='http://foo.example.com/pin'>/pin</a>
```
With the proposed relative HREFs the generated HTML is:
```
        <a href='.'>pwqgen</a>
        <a href='./m'>/m</a>
        <a href='./pin'>/pin</a>
```
The resultant absolute HREFs are valid for any view with any path root.

**Comment by iphoting** [comment]
I sure can see where you're coming from. While I understand that this will definitely workaround the issue, is this solution (of adding a '.') prefix to `href` a wide-spread practice?

Otherwise, I think you can use Sinatra's Namespaces (<http://www.sinatrarb.com/contrib/namespace.html>) to mount this app under a path prefix. The URLs generated would then be correct.

**Comment by iphoting** [comment]
Using option 1, the `config.ru` should look like this:

```ruby
map '/pwqgen' do
	map '/assets' do
		require 'sprockets'
		environment = Sprockets::Environment.new
		run environment
	end

	map '/' do
		require "#{File.dirname(__FILE__)}/pwqgen-web"
		run Sinatra::Application
	end
end
```

**Pull request closed without merging**
